title_name = "Epic Mickey 2 The Power Of Two"
title_id = "42560816" #
hash = "AA83E4F9846B59B2" # default.xex
#media_id = "4D05734B"

[[patch]]
    name = "ShowDevLevelLoad" # Adds New Option in Main Menu
    author = "Serenity"
    is_enabled = false

    [[patch.be8]]
        address = 0x82b1b18c
        value = 0x31
		
[[patch]]
    name = "GodMode"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x827CEF64
        value = 0x60000000