title_name = "Lost Planet 3"
title_id = "43430830" # CC-2096
hash = "3F74E86B6D9AC1C8" # default.xex
#media_id = "09C0B498" # Disc (USA, Europe): http://redump.org/disc/40497

[[patch]]
    name = "Unlock FPS"
    desc = "See note about framerate patches in the README."
    author = "Sowa_95"
    is_enabled = false

    [[patch.be32]]
        address = 0x82c526e8
        value = 0x60000000
    [[patch.be8]]
        address = 0x823e0a7f
        value = 0x01 # 0x00=unlimited; 0x01=60FPS; 0x02=30FPS

[[patch]]
    name = "Disable Lens Flares"
    desc = "Fixes unoccluded bright lights on-screen."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82b08160
        value = 0x39400000

[[patch]]
    name = "RTV - Decals Fix"
    desc = "Disables static decals that cause flickering with RTV rendering. Some visual artifacts may remain. Not necessary when using ROV."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822ee938
        value = 0x39600000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x829887ac
        value = 0x38a00010
