title_name = "Forza Horizon 2"
title_id = "4D530AA4" # MS-2724
hash = "64E28BBC49532373" # default.xex
#media_id = [
#    "15E4FA3D", # Disc (Europe): http://redump.org/disc/90844
#    "54FD9324", # Disc (Spain):  http://redump.org/disc/113268
#    "7C7779D1"  # Disc (USA):    http://redump.org/disc/60608
#]

[[patch]]
    name = "Disable Motion Blur"
    author = "Mutantovich"
    is_enabled = false

    [[patch.be32]]
        address = 0x92f04494
        value = 0x60000000

[[patch]]
    name = "Disable Shadows"
    author = "illusion, Sowa_95"
    is_enabled = false

    [[patch.be32]]
        address = 0x82452608
        value = 0x39600000

[[patch]]
    name = "Disable hash checks"
    desc = "Allows modifying protected files."
    author = "Sowa_95"
    is_enabled = false

    [[patch.be32]]
        address = 0x83660004
        value = 0x60000000
