title_name = "Bioshock Infinite"
title_id = "5454085D" # TT-2141
hash = "F965DFB1F254E4E2" # default.xex
#media_id = "7F5C4901" # Disc (USA, Europe): http://redump.org/disc/52057

[[patch]]
    name = "Unlock FPS"
    desc = "See note about framerate patches in the README. Alternatively use framerate option in-game, it will fully unlock FPS regardless of Xenia's vsync setting."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8253d9b0
        value = 0x60000000
    [[patch.be8]]
        address = 0x8227fe7f
        value = 0x01

[[patch]]
    name = "Disable Lens Flares"
    desc = "Fixes unoccluded bright lights on-screen."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825e6370
        value = 0x39400000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x826d7984
        value = 0x38a00010

[[patch]]
    name = "16x Anisotropic Filtering - alternative"
    desc = "Original patch doesn't filter properly, some textures look even worse than default. It might have something to do with ambient occlusion."
    author = "Sowa_95"
    is_enabled = false

    [[patch.be32]]
        address = 0x8270d7b8
        value = 0x38a00010
